apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-azurefile
  labels:
    app: redis
spec:
  serviceName: statefulset-azurefile
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: statefulset-azurefile
          image: redislabs/rejson:latest
          volumeMounts:
            - name: persistent-storage
              mountPath: /data
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: redis
  volumeClaimTemplates:
    - metadata:
        name: persistent-storage
        annotations:
          volume.beta.kubernetes.io/storage-class: azurefile-csi-nfs
      spec:
        accessModes: ["ReadWriteMany"]
        resources:
          requests:
            storage: 100Gi