apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment1
  labels:
    app: redis1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis1
  template:
    metadata:
      labels:
        app: redis1
    spec:
      containers:
      - name: redis1
        image: redislabs/rejson:latest
        volumeMounts:
        - mountPath: "/data"
          name: volume
        ports:
        - containerPort: 6379
      volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: azure-managed-disk1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment2
  labels:
    app: redis2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis2
  template:
    metadata:
      labels:
        app: redis2
    spec:
      containers:
      - name: redis2
        image: redislabs/rejson:latest
        volumeMounts:
        - mountPath: "/data"
          name: volume
        ports:
        - containerPort: 6379
      volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: azure-managed-disk2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment3
  labels:
    app: redis3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis3
  template:
    metadata:
      labels:
        app: redis3
    spec:
      containers:
      - name: redis3
        image: redislabs/rejson:latest
        volumeMounts:
        - mountPath: "/data"
          name: volume
        ports:
        - containerPort: 6379
      volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: azure-managed-disk3